### ISSUE TITLE
[✨feat] TAACO 테스트를 위한 final_dataset 구축

### ISSUE THREAD

**Issue by junggyo1020** [junggyo1020/HYU_CSE_Final#22]
## 📄 Task
- [x] final_datasets 폴더를 프로젝트 디렉토리 내에 생성하기
- [x] 각 데이터셋별로 하위 폴더를 생성 (WMT, SQuAD, CNN_DailyMail, STS 등)하는 로직을 추가
- [x] 각 데이터셋을 100개의 데이터를 포함하는 단일 파일로 저장하도록 구현
- [x] 기존 로직을 변경하지 않고 새로운 함수(`save_final_dataset_to_folder`)를 추가

### final_datasets
```
final_datasets/
├── WMT
│   ├── WMT_Entry_1.txt
│   ├── WMT_Entry_2.txt
│   └── ...
├── SQuAD
│   ├── SQuAD_Entry_1.txt
│   ├── SQuAD_Entry_2.txt
│   └── ...
├── CNN_DailyMail
│   ├── CNN_DailyMail_Entry_1.txt
│   ├── CNN_DailyMail_Entry_2.txt
│   └── ...
└── STS
    ├── STS_Entry_1.txt
    ├── STS_Entry_2.txt
    └── ...
```
### combined_scores
```
combined_scores/
├── WMT_scores.csv
├── SQuAD_scores.csv
├── CNN_DailyMail_scores.csv
└── STS_scores.csv

```
